ropensci/stplanr

R/geo-functions.R
Changes to gClip function so that it will keep the DataFrame when a SpatialPolygonsDataFrame is clipped.
=> Changes to gClip function

.travis.yml, R/data.r, man/flow.Rd, man/flowlines.Rd, man/routes_fast.Rd, man/routes_slow.Rd
Updates to .travis.yml file to install colorspace package and commenting out @family tags from data.r temporarily.
=> Changes to try to fix errors on documentation and package build

README.Rmd, README.md
* travis badge to right url
* footer to ropensci standard format
hey @Robinlovelace fixes to readme
=> fixes to readme

R/osrmfunctions.R
I think this is probably more efficient than running sapply twice.
=> Better way to convert from factor to numeric.

R/loadABS.R
Sorry about the large number of commits, I tried to squash them into one but it doesn't seem to have worked.
=> Fixes for read_table_builder

R/osrmfunctions.R
Fixing the problem identified in Robin's comment in #41.
=> Fix viaroute to correct for double backslashes in geometries.

R/toptail.R, man/toptail.Rd, man/toptailgs.Rd
Added an additional argument to toptail_gs to allow for different distances for top and tail.
=> Modify toptail and toptail_gs functions to accept vectors

R/osrmfunctions.R
Fix issue with viaroute JSON when directions include speech marks.
=> Fix to errors with viaroute JSON

R/od-funs.R
This results in 10 fold speed-up on 10000+ lines, perhaps due to omission of 'vector growing' problem caused by tmap::sbind.
=> Refactor line2route

R/osrmfunctions.R
=> Adding matched coordinates when status = "200" in nearest2spdf

R/google-functions.R
=> update travel distance

R/google-functions.R
Tested with example, not checked with devtools::check()
Works with one O and one D - now need many
=> Fix google distance api key

man/dist_google.Rd
Building documentation for #75.
=> Rebuild documentation for dist_google function.

DESCRIPTION, NEWS, R/overline.R
NB: we need to make more news updates before the next release - can you remember what's changed @richardellison?
=> Update NEWS + tweak e.g. for overline

R/route-transport-api.R, R/routes.R, man/route_cyclestreet.Rd, man/route_graphhopper.Rd, man/route_transportapi_public.Rd
Improves the use of the httr package for retrieving data by using httr to construct and encode request URIs/parameters. Also adds additional checks to ensure the result is valid and is the correct format before continuing. Addresses suggestions in #114 and #115.
=> Improve use of httr package and introduce additional checks on results

R/od-funs.R, man/line2route.Rd
Please review and test the example code @richardellison and @mem48 (who is saving many many lines) - think this is pretty robust.
=> Add list_output functionality

R/routes.R
change so that elevation change is returned correctly and added extra
outputs related to hilliness
=> Fix elevation error

vignettes/stplanr-paper.Rmd
Please review @richardellison - pretty uncontroversial I think.
=> Minor updates to the vignette

R/oneway.R
Addresses #189. I can only find one use of the functions in the current development version of the package so the other ones are likely from either other packages or the version on CRAN.
=> Fix for dplyr updates.

src/spatialnetworks.cpp
I'm keen to see how you guys navigate this, and noted this possibility for slightly leaner code
=> slight tidy of src/spatialnetworks.cpp

DESCRIPTION, R/RcppExports.R, R/catchmentArea.R, src/RcppExports.cpp
Also fixes issues with non-distance impedance values.
=> Fix error with calc_network_catchment function when using SpatialPoints

R/SpatialLinesNetwork.R, R/linefuns.R, R/od-funs.R, tests/testthat/test-calc_catchment.R
found while checking against dplyr dev
=> namespace issues

R/overline.R
=> Fix overline2 grouping issue

R/rnet-clean.R, man/rnet_breakup_vertices.Rd
=> Update description of rnet_breakup_vertices function

R/rnet_join.R, vignettes/merging-route-networks.Rmd
- changes in rnet_merge from dplyr::matches to dplyr::all_of
- add line names(rnet_merged)
=> 533 bug in the rnet merge function when defining the funs

vignettes/merging-route-networks.Rmd
- test on 3km
- update rnet_join change from dplyr::matches to dplyr::all_of
- 533 bug in the rnet merge function when defining the funs (#534)
- add 3km and large example
- add 3km and large example
- add comments
=> 3km and large exmaples

DESCRIPTION
OK with this @JosiahParry?
Will add ya, epic work with `{rsgeo}` integration, will really help our work on the NPT project.
=> Add Josiah as ctb
