ropensci/stplanr

- R/google-functions.R
Just discovered that some places have fares in there. Not sure this is the best way to implement this (please review) and happy to change things but good to know we can extract this for some places, e.g. Sao Paulo, with:
https://maps.googleapis.com/maps/api/distancematrix/json?units=metric&origins=-23.5451051924867,-46.5601207718411&destinations=-23.522306141386,-46.5048005776067&mode=transit&arrival_time=1464253200&key=
```
{
"destination_addresses" : [
"R. Amélia de Freitas Beviláqua, 13 - Vila Re, São Paulo - SP, 03661-020, Brazil"
],
"origin_addresses" : [
"Rua Amorinópolis, 97 - Vila Gomes Cardim, São Paulo - SP, 03312-020, Brazil"
],
"rows" : [
{
"elements" : [
{
"distance" : {
"text" : "8.0 km",
"value" : 8002
},
"duration" : {
"text" : "56 mins",
"value" : 3353
},
"fare" : { …
```
> Add currency and fare columns

- R/osrmfunctions.R
- man/decode_gl.Rd
- man/viaroute.Rd
Fix to decode_gl for lines with only a single point.
Initial support for OSRM API v5 has also been added to OSRM functions for viaroute/viaroute2sldf functions. Support for other functions to come soon.
> Fix to decode_gl and support for OSRM v5

- R/routes.R
Add check to graphhopper results to check if an invalid API key is returned. Fixes #110 .
> Check graphhopper result for invalid API key

- R/crs-funs.R
- R/od-funs.R
- R/radiate.R
- R/routes.R
- R/toptail.R
- man/buff_geo.Rd
- man/route_cyclestreet.Rd
- tests/testthat/test-calc_catchment.R
- tests/testthat/test-route_cyclestreet.R
I think we should additionally do this for the other routing functions so people can go back to the raw json files spat out by these things. Will put in a separate issue for splitting out the code used to interpret the json objects and look into the implications of this for the `line2route()` wrapper function.
Comments welcome.
> Add save_raw functionality to route_cyclestreet

- R/od-funs.R
When calling `line2route` with `nrow(l) == 1` 
I get an error: 
> Error in FUN(from = c(ldf$fx[2], ldf$fy[2]), to = c(ldf$tx[2], ldf$ty[2])
This fixes that and also simplifies some other code in line2route.
> Allow single value lines to be passed to line2route

- R/od-funs.R
`tryCatch` doesn't work in `foreach` but there is an option to `pass` the error through.
```r
> rf_with_err = line2route(flowlines[1:2,], reporterrors = T, n_processes = 2)
> rf_with_err$error
[1] "Error: Too short: journeys must be longer than 4 metres. (Your requested journey was 0 metres)."
[2] NA
```
> Fix error handling in parallel

- R/SpatialLinesNetwork.R
- man/find_network_nodes.Rd
- man/plot-SpatialLinesNetwork-ANY-method.Rd
- man/sum_network_routes.Rd
- man/summary-SpatialLinesNetwork-method.Rd
- man/weightfield.Rd
This PR speeds up calculating combinations of routes using a SpatialLinesNetwork. This is useful if you want to calculate all routes from a single origin to many destinations or many origins to the same set of destinations.
> Small change to sum_network_routes function

- R/SpatialLinesNetwork.R
It turns out this was a discrepancy between zero-based indexes in C++ and one-based indexes in R. I'm surprised it has taken this long to run into an issue because of it!
> Fixes the issue @Robinlovelace noticed in #186

- R/google-functions.R
- man/dist_google.Rd
I trust no code needed here. The former man entries from `route_cyclestreet` described single vectors for `from` and `to`, but these can actually be matrices or data.frames with multiple values. Main problem this solves is the limitation of the google API to 100 queries, so this now prints useful error messages when this limit (or whatever else it might be) is exceeded. The API *should* then always return an `error_message` parameter, but i've gone the safest route of simply using a `grepl` just in case it's not exactly called `error_message`.
> add stop on useful warnings from google API

- R/SpatialLinesNetwork.R
As @mem48 suggested, needed to add do_union = FALSE to the summarise call to avoid points being reordered based on the X coordinate.
> Fix #249 by adding do_union = FALSE.

- R/routes.R
I was getting this error: 
Error in obj$paths$points[[1]][[1]][, 1:2] : 
incorrect number of dimensions
The points were the next line down so changing the first '1' to a '2' fixes this.
> update changes to the graphhopper api

- R/route.R
[This code](https://github.com/ropensci/stplanr/issues/247#issuecomment-511129731) from #247 works with this PR and give this message:
``` r
r <- route_dodgr(from, to, net = area99_sf)
#> unable to trace path number 10
```
Admittedly the "number 10" is not the clearest way to convey that, but that can be tweaked later if needed - it should only arise very (very) rarely when paths simply can not be traced at all.
> fixes #247 (again)

- R/route.R
This ensures that `dodgr` routes only through the largest connected component, so should reduce incidence of paths that do no connect
> more tweaks for #247

- R/route.R
I have attempted to improve the error message(s) that are printed when the function cannot route between and origin and destination. The message that is printed where there are more than one path that cannot be routed is a longe string of concatenated index numbers which is confusing, and does not indicate how many failed. It now does.
> Improved error messages

- NEWS.md
- R/overline.R
The LINESTRING geometry check in `overline2()` does not accept geometry column names other than `"geometry"`:
``` r
library(sf)
#> Linking to GEOS 3.7.2, GDAL 2.4.2, PROJ 5.2.0
library(stplanr)
sf <- st_sf(
data.frame(
id = c("l_1", "l_2", "l_3"),
count = c(1, 1, 1)
),
other_than_geometry = list(
st_linestring(cbind(c(0,0,1,1,2,2,3,3),c(0,0,1,1,2,2,3,3))),
st_linestring(cbind(c(0,0,1,1,2,2,3),c(0,0,1,1,2,2,2))),
st_linestring(cbind(c(0,0,1,1,3),c(0,0,1,1,1)))
)
)
overline(sf, fun = sum(), attrib = "count")
#> Error in overline2(x = sl, attrib = attrib): Only LINESTRING is supported
```
To make `overline()` independent of the name of the geometry column, access to the geometries by `x$geometry` could be replaced with `sf::st_geometry(x)`.
<details>
<summary>Session info</summary>
``` r …
```
> Make `overline()` independent of the sf geometry column name

- .github/workflows/R-CMD-check.yaml
Thanks @Robinlovelace for the best template I've yet seen for a github actions matrix build. I copied most of it over to `gtfsrouter`, but needed this line to [make it work](https://github.com/ATFutures/gtfs-router/runs/738589860?check_suite_focus=true) on all of your currently commented-out systems. Most of your [fails look](https://github.com/ropensci/stplanr/runs/702383935?check_suite_focus=true) [like the](https://github.com/ropensci/stplanr/runs/702383917?check_suite_focus=true) [same thing](https://github.com/ropensci/stplanr/runs/702383910?check_suite_focus=true) so this should fix?
> This shoiuld fix failing matrix systems

- R/overline.R
Small tweaks to overline2 to reduce compute time using data.table and dplyr functions
```
routes <- pct::get_pct_routes_fast("west-yorkshire", geography = "lsoa")
> system.time({
+   rnet1 <- stplanr::overline2(routes, c("bicycle","dutch_slc","ebike_slc"))
+ })
user  system elapsed 
93.31    2.83   99.25 
> system.time({
+   rnet2 <- overline2(routes, c("bicycle","dutch_slc","ebike_slc"))
+ })
user  system elapsed 
86.86    0.83   88.22 
> identical(rnet1, rnet2)
[1] TRUE
```
> speed boost to overline

- R/SpatialLinesNetwork.R
- man/route_local.Rd
- man/sln2points.Rd
- man/sum_network_routes.Rd
Reprex of the current results: 
``` r
remotes::install_github("ropensci/stplanr", ref = "c0e1e9c1f18e4f94f64fe4e81e2b6c0e4b4720c4")
#> Using github PAT from envvar GITHUB_PAT
#> Skipping install of 'stplanr' from a github remote, the SHA1 (c0e1e9c1) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(stplanr)
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
sln_sf <- SpatialLinesNetwork(route_network_sf)
sum_network_routes(sln_sf, start = c(1, 2), end = c(2, 3)) # regular
#> Simple feature collection with 2 features and 3 fields
#> geometry type:  LINESTRING
#> dimension:      XY
#> bbox:           xmin: -1.550964 ymin: 53.82387 xmax: -1.546613 ymax: 53.82496
#> geographic CRS: WGS 84
#> # A tibble: 2 x 4
#> …
```
> Fix network routing with identical nodes

- R/overline.R
Fix for #466 when due to `s2` now being in the `sf` package `st_make_grid` does not always work for geographical CRS. See https://github.com/r-spatial/sf/issues/1777 
Fix is to manually make the grid a little bit bigger which makes sure the points are always inside the grid.
Should be tested in some non-UK locations to make sure this always works.
> fix for #466

- DESCRIPTION
- R/line_via.R
- tests/testthat/test-mats2line.R
This PR closes #539. 
It refactors `mats2line()` by utilizing `vec_interleave()` and `sfheaders::sfc_linestring()`. It adds an explicit dependency on vctrs (minimum version 0.4.0 as that is when vec_interleave() was added). 
> Note that vctrs is implicitly imported at present, this just makes it explicit. 
An additional test is added to verify the validity of the linestrings that are created by `mats2line()`.
Checks are additionally added to verify that `mat1` and `mat2` are of compatible sizes.
> refactor mats2line() for speed enhancement

- R/rnet_join.R
- man/rnet_group.Rd
- vignettes/merging-route-networks.Rmd
Closes #554
- **add handle_strings to rnet_join**
- **remove brower**
- **remove lines**
- **fixing a bug**
- **Update merging route networks vignette**
- **Eval false on big vignette**
> handle strings

- DESCRIPTION
- NEWS.md
- R/linefuns.R
- R/rnet_join.R
- man/line_segment.Rd
- man/rnet_join.Rd
- man/rnet_merge.Rd
- reprexes/test-rnet_join.R
See https://github.com/JosiahParry/rsgeo/issues/42 which this mitigates
> Use output of rsgeo for n_segments (#552)

- R/rnet_group.R
- man/rnet_group.Rd
> Only run rnet_group() examples when igraph installed
